FROM christianberg/postgresql-9.3
MAINTAINER Christian Berg <berg.christian@gmail.com>

EXPOSE 5432

USER postgres
CMD ["/usr/lib/postgresql/9.3/bin/postgres", "--config_file=/etc/postgresql/9.3/main/postgresql.conf"]
